---
# 7 Days to Die Server - Existing Container Inventory
#
# This inventory targets an existing LXD container via ProxyJump through the LXD host.
#
# Usage:
#   ansible-playbook playbooks/sdtd_server_continue.yml -i inventory/sdtd_server_continue

all:
  children:
    sdtd_container:
      hosts:
        sdtd-server:
          ansible_host: 192.168.10.173
          ansible_user: adam
          ansible_python_interpreter: /usr/bin/python3
          # ProxyJump through LXD host to reach the container
          ansible_ssh_common_args: >-
            -o ProxyJump=adam@192.168.42.5
            -o StrictHostKeyChecking=no
            -o UserKnownHostsFile=/dev/null
