---
# Ansible Galaxy collection requirements
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
  # POSIX-specific modules (authorized_key, sysctl, etc.)
  - name: ansible.posix
    version: ">=1.5.0"

  # Community general collection (includes LXD modules, dconf, etc.)
  - name: community.general
    version: ">=8.0.0"

  # Crypto collection for SSH key generation
  - name: community.crypto
    version: ">=2.0.0"

  # Docker collection for container management (used by Molecule)
  - name: community.docker
    version: ">=3.0.0"
