---
# Conduwuit Server Role — Prerequisites Tasks

- name: Conduwuit Prerequisites | Install required apt packages
  ansible.builtin.apt:
    name:
      - curl
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true
