---
# Molecule create playbook for LXD E2E test
# Creates an LXD container for testing

- name: Create LXD container
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    molecule_inventory:
      all:
        hosts:
          ansible-test-noble:
            ansible_connection: community.general.lxd
            ansible_lxd_remote: local
            ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Create LXD container
      community.general.lxd_container:
        name: ansible-test-noble
        state: started
        source:
          type: image
          mode: pull
          server: https://cloud-images.ubuntu.com/releases/
          protocol: simplestreams
          alias: "24.04"
        profiles:
          - default
        config:
          security.nesting: "true"
        wait_for_ipv4_addresses: true
        timeout: 300
      register: lxd_container

    - name: Wait for container to be ready
      ansible.builtin.pause:
        seconds: 10

    - name: Install Python in container
      ansible.builtin.command: lxc exec ansible-test-noble -- apt-get update
      changed_when: true

    - name: Install Python3 in container
      ansible.builtin.command: lxc exec ansible-test-noble -- apt-get install -y python3
      changed_when: true

    - name: Populate instance config dict
      ansible.builtin.set_fact:
        instance_conf_dict:
          instance: ansible-test-noble
          address: ansible-test-noble
          user: root
          port: "22"
          identity_file: ""
          connection: community.general.lxd
          ansible_lxd_host: ansible-test-noble
          ansible_lxd_remote: local

    - name: Convert instance config to list
      ansible.builtin.set_fact:
        instance_conf: "{{ [instance_conf_dict] }}"

    - name: Dump instance config
      ansible.builtin.copy:
        content: "{{ instance_conf | to_nice_yaml(indent=2) }}"
        dest: "{{ molecule_instance_config }}"
        mode: "0600"
