---
# Inventory for Mikolaj's Framework laptop.

all:
  hosts:
    mikolaj-framework:
      ansible_host: 192.168.10.200
      ansible_user: mikolaj
      ansible_python_interpreter: /usr/bin/python3

  vars:
    target_user: mikolaj
